version: '3'

services:

  app:
    build:
      context: node
      dockerfile: Dockerfile.prod
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0  --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysqlData:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mysqlData:
